description = "规划详细的章节结构和情节安排"

prompt = """
基于故事大纲制定详细的章节规划，智能应用写作方法。

用户需求：{{args}}

## 执行步骤

### 1. 读取配置和方法
读取 .specify/config.json 的 "method" 字段：
- 如果是 "hybrid"，检查 "hybridScheme" 详细方案
- 参考对应模板：spec/presets/[method]/outline.md

### 2. 初始化章节文件
执行脚本：!{.specify/scripts/bash/setup-outline.sh}

### 3. 加载故事大纲
读取 stories/*/story.md 理解故事内容。

### 4. 应用方法规划章节

**三幕结构**
- 第一幕：25%章节，建立设置
- 第二幕：50%章节，冲突发展
- 第三幕：25%章节，高潮解决

**英雄之旅**
将12个阶段合理分配到章节中。

**故事圈**
8个步骤循环安排，每步2-3章。

**七点结构**
精确定位7个关键节点：
- 钩子（第1章）
- 情节点1（25%处）
- 收紧点（37%处）
- 中点（50%处）
- 情节点2（75%处）
- 黑暗时刻（90%处）
- 解决（结尾）

**皮克斯公式**
6步因果链条贯穿全书。

**雪花十步**
基于场景列表驱动章节。

**混合方法**
- 主线按主方法
- 支线按次方法
- 章节内按微观方法

### 5. 生成章节规划
使用 write_file 创建 outline.md：

# 章节规划

## 总体结构
- 总章节数：[数量]
- 每章字数：[范围]
- 更新计划：[频率]

## 方法映射
[说明每章对应的方法节点]

## 卷部划分
[如有多卷，划分主题]

## 详细章节
### 第一章：[标题]
- 字数：[目标]
- 要点：[3-5个]
- 方法节点：[对应位置]

[继续其他章节...]

### 6. 完成报告
✅ 章节规划完成！
- 方法：[使用的结构]
- 章节：[总数]
- 预计：[总字数]
- 下一步：使用 /write 开始创作

## 注意事项
- 严格按照方法要求分配节奏
- 关键节点位置必须准确
- 混合方法要协调好层级
"""