description = "追踪写作进度和状态，生成进度报告"

prompt = """
追踪写作进度，管理创作状态。

用户要求：{{args}}

## 执行步骤

### 1. 读取追踪数据
加载所有追踪文件：
- spec/tracking/character-state.json
- spec/tracking/plot-tracker.json
- spec/tracking/relationships.json
- spec/tracking/timeline.json

### 2. 收集进度信息
执行脚本：!{.specify/scripts/bash/track-progress.sh}

统计数据：
- 已写章节数
- 总字数
- 各章节状态
- 剩余工作量

### 3. 生成进度报告

**整体进度**
```
📊 写作进度报告

总体进度：████████░░ 40%
已完成：10/25章
总字数：25,000/60,000字

本周进度：
- 完成章节：2章
- 新增字数：5,000字
- 日均产出：714字
```

**章节详情**
```
章节状态：
✅ 第1章：完成（2,500字）
✅ 第2章：完成（2,300字）
📝 第3章：草稿（1,800字）
⏸️ 第4章：构思中
❌ 第5章：待写
```

**情节追踪**
```
主线进度：
[=====>    ] 50% - 冲突升级阶段

支线状态：
- 感情线：[===>  ] 30%
- 成长线：[====> ] 40%
```

**角色状态**
```
角色发展：
- 主角：成长期（第二阶段）
- 反派：潜伏期
- 配角A：关系转变中
```

### 4. 分析创作节奏
```
创作分析：
- 平均速度：500字/小时
- 最高产出：第7章（3,200字）
- 创作高峰：晚上8-10点
- 预计完成：30天后
```

### 5. 生成建议
```
📝 创作建议：
1. 当前节奏良好，保持每日更新
2. 第10章是关键转折，需要重点准备
3. 支线进度偏慢，建议下章推进
4. 人物关系可以增加冲突
```

### 6. 更新追踪文件
使用 edit_file 更新各追踪文件的最新状态。

### 7. 完成报告
✅ 进度追踪完成！
- 总进度：[百分比]
- 本周产出：[字数]
- 预计完成：[日期]
- 下一步：[建议]

## 注意事项
- 定期更新追踪数据
- 关注关键节点进度
- 及时调整创作计划
- 保持稳定产出
"""