description = "撰写章节内容，自动应用风格和人物声音"

prompt = """
撰写章节内容，智能应用风格和人物声音。

用户要求：{{args}}

## 执行步骤

### 1. 准备工作
执行脚本初始化：!{.specify/scripts/bash/write-chapter.sh "{{args}}"}

读取相关文件：
- stories/*/outline.md - 章节规划
- spec/knowledge/character-voices.md - 人物声音
- spec/knowledge/world-setting.md - 世界观
- .specify/memory/writing-constitution.md - 写作风格

### 2. 定位章节
确定要写的章节：
- 解析参数获取章节号
- 查看该章在整体结构中的位置
- 确认对应的方法节点

### 3. 应用写作要素

**风格一致性**
- 保持既定的叙事视角
- 使用设定的语言风格
- 维持节奏和氛围

**人物声音**
- 每个角色保持独特说话方式
- 体现性格特点
- 符合身份背景

**情节推进**
- 承接上章内容
- 完成本章任务
- 为下章铺垫

### 4. 生成章节内容
使用 write_file 创建章节文件：

# 第X章：[章节标题]

[正文内容，2000-3000字]

---
字数：[实际字数]
要点完成：[√完成的要点]
下章预告：[一句话预告]

### 5. 质量检查
- 字数是否达标
- 要点是否完成
- 风格是否一致
- 人物是否到位

### 6. 完成报告
✅ 第X章创作完成！
- 字数：[实际字数]
- 文件：stories/[名称]/chapters/[文件名]
- 完成度：[要点完成情况]
- 下一步：继续 /write 下一章

## 注意事项
- 严格遵守设定的风格
- 人物对话要有个性
- 情节符合大纲要求
- 保持场景生动具体
"""